version: "3.2"
services:
  clipper_bid_keeper:
    build: .
    image: auction-keeper
    env_file:
      - .env
    volumes:
      - $PWD/hush:/home/keeper/hush
      - $PWD/model:/home/keeper/model
    command: >
      bash -c "python main.py --rpc-host=${ETH_RPC} --eth-from=${ETH_FROM} \
      --eth-key='key_file=/home/keeper/hush/auction.json,pass_file=/home/keeper/hush/auction.pass' \
      --bid-only --type='clip' --from-block=${BLOCK_NUMBER} --ilk=${ILK} \
      --model=./model/model.sh"
   
  clipper_bid_keeper:
     build: .
     image: auction-keeper
     env_file:
       - .env
     volumes:
       - $PWD/hush:/home/keeper/hush
       - $PWD/model:/home/keeper/model
     command: >
       bash -c "python main.py --rpc-host=${ETH_RPC} --eth-from=${ETH_FROM} \
       --eth-key='key_file=/home/keeper/hush/auction.json,pass_file=/home/     keeper/hush/auction.pass' \
       --bid-only --type='clip' --from-block=${BLOCK_NUMBER} --ilk=${ILK} \
       --model=./model/model.sh"

